apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-prova-api-deploy
  labels:
    app: infra-prova-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infra-prova-api
  template:
    metadata:
      labels:
        app: infra-prova-api
    spec:
      containers:
        - name: infra-prova-api
          image: infra-prova-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
